# Generated by Django 4.1.13 on 2024-04-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('oid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=30)),
                ('salary', models.FloatField()),
                ('registration', models.CharField(max_length=50)),
            ],
        ),
    ]
