# Generated by Django 4.1.13 on 2024-04-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapi', '0002_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
