# Generated by Django 4.1.13 on 2024-04-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapi', '0003_alter_employee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='oid',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_registration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_role',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
